-- Love2D runtime for vector tables generated by svg2ticvec.py.
--
-- Commands:
-- {"c", color_or_role}      set color role or literal color
-- {"w", width}              set stroke width for outline commands
-- {"m", x, y}               move cursor
-- {"l", x, y}               line to
-- {"z"}                     close current path
-- {"o", cx, cy, r}          circle outline
-- {"f", cx, cy, r}          filled circle
-- {"p", x1, y1, ...}        filled polygon
-- {"r", x, y, w, h}         rectangle outline
-- {"b", x, y, w, h}         filled rectangle

local M = {}

local DEFAULT_COLOR = {1, 1, 1, 1}

local function copy_color(color)
  return {color[1] or 1, color[2] or 1, color[3] or 1, color[4] or 1}
end

local function normalize_color(value, palette)
  if type(value) == "string" then
    local mapped = palette[value]
    if type(mapped) == "table" then
      return copy_color(mapped)
    end
    return copy_color(DEFAULT_COLOR)
  end

  if type(value) == "table" then
    return copy_color(value)
  end

  if type(value) == "number" then
    local mapped = palette[value]
    if type(mapped) == "table" then
      return copy_color(mapped)
    end
  end

  return copy_color(DEFAULT_COLOR)
end

local function find_loaded_vector(env, symbol_name)
  if symbol_name then
    if type(env[symbol_name]) == "table" then
      return env[symbol_name]
    end
    error(("vector symbol %q was not found in loaded file"):format(symbol_name))
  end

  local found_name = nil
  local found_value = nil

  for key, value in pairs(env) do
    if type(value) == "table" then
      if found_value ~= nil then
        error("loaded file defined multiple tables; pass an explicit symbol name")
      end
      found_name = key
      found_value = value
    end
  end

  if found_value ~= nil then
    return found_value, found_name
  end

  error("loaded file did not return a table and did not define one in its chunk environment")
end

function M.loadvec(path, symbol_name)
  local chunk, err = love.filesystem.load(path)
  if not chunk then
    error(("failed to load vector file %q: %s"):format(path, err))
  end

  local env = {}
  setmetatable(env, {__index = _G})

  if setfenv then
    setfenv(chunk, env)
  end

  local ok, result = pcall(chunk)
  if not ok then
    error(("failed to execute vector file %q: %s"):format(path, result))
  end

  if type(result) == "table" then
    return result
  end

  return find_loaded_vector(env, symbol_name)
end

function M.drawvec(v, x, y, s, palette)
  s = s or 1
  palette = palette or {}

  local cx, cy = 0, 0
  local sx, sy = 0, 0
  local sw = 1
  local color = copy_color(DEFAULT_COLOR)

  local lg = love.graphics
  local prev_r, prev_g, prev_b, prev_a = lg.getColor()
  local prev_width = lg.getLineWidth()
  local prev_join = lg.getLineJoin()

  lg.setLineJoin("bevel")

  for i = 1, #v do
    local p = v[i]
    local cmd = p[1]

    if cmd == "c" then
      color = normalize_color(p[2], palette)
      lg.setColor(color)
    elseif cmd == "w" then
      sw = p[2]
      if sw < 1 then
        sw = 1
      end
    elseif cmd == "m" then
      cx = x + p[2] * s
      cy = y + p[3] * s
      sx = cx
      sy = cy
    elseif cmd == "l" then
      local nx = x + p[2] * s
      local ny = y + p[3] * s
      lg.setColor(color)
      lg.setLineWidth(sw * s)
      lg.line(cx, cy, nx, ny)
      cx = nx
      cy = ny
    elseif cmd == "z" then
      lg.setColor(color)
      lg.setLineWidth(sw * s)
      lg.line(cx, cy, sx, sy)
      cx = sx
      cy = sy
    elseif cmd == "o" then
      lg.setColor(color)
      lg.setLineWidth(sw * s)
      lg.circle("line", x + p[2] * s, y + p[3] * s, p[4] * s)
    elseif cmd == "f" then
      lg.setColor(color)
      lg.circle("fill", x + p[2] * s, y + p[3] * s, p[4] * s)
    elseif cmd == "p" then
      local pts = {}
      for j = 2, #p, 2 do
        pts[#pts + 1] = x + p[j] * s
        pts[#pts + 1] = y + p[j + 1] * s
      end
      lg.setColor(color)
      lg.polygon("fill", pts)
    elseif cmd == "r" then
      lg.setColor(color)
      lg.setLineWidth(sw * s)
      lg.rectangle("line", x + p[2] * s, y + p[3] * s, p[4] * s, p[5] * s)
    elseif cmd == "b" then
      lg.setColor(color)
      lg.rectangle("fill", x + p[2] * s, y + p[3] * s, p[4] * s, p[5] * s)
    end
  end

  lg.setColor(prev_r, prev_g, prev_b, prev_a)
  lg.setLineWidth(prev_width)
  lg.setLineJoin(prev_join)
end

return M
