-- TIC-80 SVG Lite runtime
-- Draws simple vector tables generated by svg2ticvec.py.
--
-- Commands:
-- {"c", color_or_role}      set TIC-80 color or palette role
-- {"w", width}              set stroke width for outline commands
-- {"m", x, y}               move cursor
-- {"l", x, y}               line to
-- {"z"}                     close current path
-- {"o", cx, cy, r}          circle outline
-- {"f", cx, cy, r}          filled circle
-- {"p", x1, y1, ...}        filled polygon
-- {"r", x, y, w, h}         rectangle outline
-- {"b", x, y, w, h}         filled rectangle

local function fillpoly(points,col)
 local n=#points/2
 if n<3 then return end

 local miny,maxy=points[2],points[2]
 for i=2,#points,2 do
  local y=points[i]
  if y<miny then miny=y end
  if y>maxy then maxy=y end
 end

 local ys=math.floor(miny)
 local ye=math.ceil(maxy)

 for y=ys,ye do
  local scan=y+0.5
  local xs={}

  for i=1,n do
   local j=i+1
   if j>n then j=1 end
   local x1=points[i*2-1]
   local y1=points[i*2]
   local x2=points[j*2-1]
   local y2=points[j*2]

   if y1~=y2 then
    local ymin=y1
    local ymax=y2
    if ymin>ymax then
     ymin,ymax=ymax,ymin
     x1,x2=x2,x1
     y1,y2=y2,y1
    end

    if scan>=ymin and scan<ymax then
     local t=(scan-y1)/(y2-y1)
     xs[#xs+1]=x1+t*(x2-x1)
    end
   end
  end

  table.sort(xs)
  for i=1,#xs-1,2 do
   line(xs[i],y,xs[i+1],y,col)
  end
 end
end

local function drawthickline(x1,y1,x2,y2,w,col)
 if w<=1 then
  line(x1,y1,x2,y2,col)
  return
 end

 local dx=x2-x1
 local dy=y2-y1
 local len=math.sqrt(dx*dx+dy*dy)
 if len<0.0001 then
  circ(x1,y1,w/2,col)
  return
 end

 local hw=w/2
 local nx=-dy/len*hw
 local ny=dx/len*hw
 fillpoly({
  x1+nx,y1+ny,
  x2+nx,y2+ny,
  x2-nx,y2-ny,
  x1-nx,y1-ny,
 },col)
 circ(x1,y1,hw,col)
 circ(x2,y2,hw,col)
end

local function drawrectstroke(x,y,w,h,sw,col)
 if sw<=1 then
  rectb(x,y,w,h,col)
  return
 end

 rect(x-sw/2,y-sw/2,w+sw,sw,col)
 rect(x-sw/2,y+h-sw/2,w+sw,sw,col)
 rect(x-sw/2,y+sw/2,sw,h-sw,col)
 rect(x+w-sw/2,y+sw/2,sw,h-sw,col)
end

local function drawcirclestroke(x,y,r,sw,col)
 if sw<=1 then
  circb(x,y,r,col)
  return
 end

 local half=sw/2
 local r0=math.max(0,math.floor(r-half))
 local r1=math.max(r0,math.ceil(r+half))
 for rr=r0,r1 do
  circb(x,y,rr,col)
 end
end

function drawvec(v,x,y,s,pal)
 s=s or 1
 pal=pal or {}
 local cx,cy=0,0
 local sx,sy=0,0
 local col=12
 local sw=1

 for i=1,#v do
  local p=v[i]
  local cmd=p[1]

  if cmd=="c" then
   if type(p[2])=="number" then
    col=p[2]
   else
    col=pal[p[2]] or 12
   end

  elseif cmd=="w" then
   sw=p[2]
   if sw<1 then sw=1 end

  elseif cmd=="m" then
   cx=x+p[2]*s
   cy=y+p[3]*s
   sx=cx
   sy=cy

  elseif cmd=="l" then
   local nx=x+p[2]*s
   local ny=y+p[3]*s
   drawthickline(cx,cy,nx,ny,sw*s,col)
   cx=nx
   cy=ny

  elseif cmd=="z" then
   drawthickline(cx,cy,sx,sy,sw*s,col)
   cx=sx
   cy=sy

  elseif cmd=="o" then
   drawcirclestroke(x+p[2]*s,y+p[3]*s,p[4]*s,sw*s,col)

  elseif cmd=="f" then
   circ(x+p[2]*s,y+p[3]*s,p[4]*s,col)

  elseif cmd=="p" then
   local pts={}
   for j=2,#p,2 do
    pts[#pts+1]=x+p[j]*s
    pts[#pts+1]=y+p[j+1]*s
   end
   fillpoly(pts,col)

  elseif cmd=="r" then
   drawrectstroke(x+p[2]*s,y+p[3]*s,p[4]*s,p[5]*s,sw*s,col)

  elseif cmd=="b" then
   rect(x+p[2]*s,y+p[3]*s,p[4]*s,p[5]*s,col)
  end
 end
end
