-- TIC-80 SVG Lite runtime
-- Draws simple vector tables generated by svg2ticvec.py.
--
-- Commands:
-- {"c", color}              set TIC-80 color
-- {"m", x, y}               move cursor
-- {"l", x, y}               line to
-- {"z"}                     close current path
-- {"o", cx, cy, r}          circle outline
-- {"f", cx, cy, r}          filled circle
-- {"r", x, y, w, h}         rectangle outline
-- {"b", x, y, w, h}         filled rectangle

function drawvec(v,x,y,s)
 s=s or 1
 local cx,cy=0,0
 local sx,sy=0,0
 local col=12

 for i=1,#v do
  local p=v[i]
  local cmd=p[1]

  if cmd=="c" then
   col=p[2]

  elseif cmd=="m" then
   cx=x+p[2]*s
   cy=y+p[3]*s
   sx=cx
   sy=cy

  elseif cmd=="l" then
   local nx=x+p[2]*s
   local ny=y+p[3]*s
   line(cx,cy,nx,ny,col)
   cx=nx
   cy=ny

  elseif cmd=="z" then
   line(cx,cy,sx,sy,col)
   cx=sx
   cy=sy

  elseif cmd=="o" then
   circb(x+p[2]*s,y+p[3]*s,p[4]*s,col)

  elseif cmd=="f" then
   circ(x+p[2]*s,y+p[3]*s,p[4]*s,col)

  elseif cmd=="r" then
   rectb(x+p[2]*s,y+p[3]*s,p[4]*s,p[5]*s,col)

  elseif cmd=="b" then
   rect(x+p[2]*s,y+p[3]*s,p[4]*s,p[5]*s,col)
  end
 end
end
